version: '3.9'

services:
  debts-management:
    build: .
    container_name: debts-management
    restart: unless-stopped
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - ./app:/app
    networks:
      - dm
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - dm
networks:
  dm:
    driver: bridge